name: women_safety_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  firebase_core: ^2.30.0
  firebase_database: ^10.5.0
  flutter_phone_direct_caller: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bg.png   