// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAUSrPJGgm-dfVN9YrmAelmZlt50adI4',
    appId: '1:1008307200829:web:a8bc74ec7258a738b21b54',
    messagingSenderId: '1008307200829',
    projectId: 'safety-app-46e36',
    authDomain: 'safety-app-46e36.firebaseapp.com',
    databaseURL: 'https://safety-app-46e36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-app-46e36.firebasestorage.app',
    measurementId: 'G-V0R6D9G64S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5AyPvgVJjQhzxfRDZpQmfE_-BbZC_sbE',
    appId: '1:1008307200829:android:5e854c6381c75f7eb21b54',
    messagingSenderId: '1008307200829',
    projectId: 'safety-app-46e36',
    databaseURL: 'https://safety-app-46e36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-app-46e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO9D3hLKit0RB7S4kkSaTHE0nZbdddwlw',
    appId: '1:1008307200829:ios:7b51295e7e060615b21b54',
    messagingSenderId: '1008307200829',
    projectId: 'safety-app-46e36',
    databaseURL: 'https://safety-app-46e36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-app-46e36.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO9D3hLKit0RB7S4kkSaTHE0nZbdddwlw',
    appId: '1:1008307200829:ios:7b51295e7e060615b21b54',
    messagingSenderId: '1008307200829',
    projectId: 'safety-app-46e36',
    databaseURL: 'https://safety-app-46e36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-app-46e36.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbAUSrPJGgm-dfVN9YrmAelmZlt50adI4',
    appId: '1:1008307200829:web:dc4ef80e5b455ccdb21b54',
    messagingSenderId: '1008307200829',
    projectId: 'safety-app-46e36',
    authDomain: 'safety-app-46e36.firebaseapp.com',
    databaseURL: 'https://safety-app-46e36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safety-app-46e36.firebasestorage.app',
    measurementId: 'G-NYH9GN0MHM',
  );
}
